@node Элементы Формы, Элемент формы Поле, Форма, Top
@chapter Элементы Формы

@menu
* Элемент формы Группа::
* Элемент формы Таблица::
* Элемент формы Кнопка::
* Элемент формы Декорация::
* Дополнение элемента формы::
* Контекстное меню элементов формы::
@end menu

@node Элемент формы Группа, Элемент формы Таблица, Элементы Формы, Элементы Формы
@section Элемент формы Группа

Элемент формы Группа предназначен для группировки других
элементов формы. Это могут быть группы полей, группы страниц,
группы команд. Также для элементов типа Таблица можно создавать
группы колонок. Группы могут быть вложенными друг в  друга.
Свойство Вид элемента формы Группа может принимать значения:

@itemize @bullet
@item
Обычная группа . Элемент формы, предназначенный для логической
группировки других элементов формы (рис. 2.70).
Элемент Обычная группа может не выделяться в  форме,
выполняя при этом функции группировки других элементов.
Выделением группы управляет свойство Отображение .

@image{./Kartinki/2_70}
Рис. 2.70

@item
Командная панель . Элемент формы, предназначенный для груп-
пировки кнопок и  групп команд. Наполнение командной панели
конкретными командами определяется свойством Источник команд .
На рис. 2.71 источником команд является таблица формы,
отображающая динамический список.

@image{./Kartinki/2_71}
Рис.2.71

Помимо отдельных кнопок в  командную панель можно добавлять
подчиненные группы следующего вида (рис. 2.72):

@itemize @minus
@item
Подменю . Элемент формы, представляющий собой выпада-
ющее меню.

@item
Группа кнопок . Элемент формы, позволяющий сгруппировать
кнопки в  логические группы. Сам элемент не отображается
на форме, но кнопки в  группе можно расположить компактно
(без отступов друг от друга).

@image{./Kartinki/2_72}
Рис. 2.72
@end itemize

@item
Страницы . Элемент формы, предназначенный для организации
панели с закладками. Для того чтобы добавить на такую панель
страницы, необходимо добавить столько вложенных групп вида
Страница , сколько страниц должно быть у панели (рис. 2.73).

@itemize @minus
@item
Страница . Элемент формы, который может быть создан
только как подчиненный элементу Страницы . Представляет
собой подчиненную группу-страницу с данными
(в нашем случае открыта страница «Изображение»).
В пользовательском режиме работы страницы, на которых
отсутствуют данные, не отображаются.

@image{./Kartinki/2_73}
Рис .2.73
@end itemize

@item
Группа колонок   – позволяет объединять колонки в  таблице
(рис. ниже). С помощью группы этого вида можно изменять
правило группировки колонок.

@image{./Kartinki/2_74}
Рис. 2.74
@end itemize

@node Элемент формы Таблица, Элемент формы Кнопка, Элемент формы Группа, Элементы Формы
@section Элемент формы Таблица

Элемент формы Таблица предназначен для отображения и  редактирования
различных табличных данных (рис. 2.75). Это может быть
динамический список, табличная часть, список значений и  т. д.
У таблицы формы могут быть свои командные панели, контекстные
меню. Поля колонок элемента Таблица могут быть сгруппированы
(см. рис. 2.74).

@image{./Kartinki/2_75}
Рис. 2.75

@node Элемент формы Кнопка, Элемент формы Декорация, Элемент формы Таблица, Элементы Формы
@section Элемент формы Кнопка

Элемент формы Кнопка предназначен для отображения кнопок
и  гиперссылок, при нажатии на которые выполняются связанные
с ними команды. Кнопки могут быть подчинены командной
панели. В зависимости от этого свойство Вид элемента формы Кнопка
может принимать значения:
@itemize

@item
Кнопка , Кнопка командной панели . Элемент представляет собой
обыкновенную кнопку, расположенную непосредственно в  форме
или в  составе командной панели (рис. 2.76). Если для кнопки
не назначена команда, которая будет выполняться при нажатии,
то кнопка в  пользовательском режиме не отображается.

@image{./Kartinki/2_76}
Рис. 2.76. Элементы формы «Кнопка» и «Кнопка командной панели»

@item
Гиперссылка , Гиперссылка командной панели . Кнопка формы
или кнопка командной панели, отображающаяся в  виде гипер-
ссылки (рис. 2.77). Если для гиперссылки не назначена команда,
которая будет выполняться при нажатии, то гиперссылка
в  пользовательском режиме не отображается.

@image{./Kartinki/2_77}
Рис. 2.77. Элементы формы «Гиперссылка» и «Гиперссылка командной панели»
@end itemize

@node Элемент формы Декорация, Дополнение элемента формы, Элемент формы Кнопка, Элементы Формы
@section Элемент формы Декорация
Элемент формы Декорация представляет собой оформительский
элемент формы. Декорация может представлять собой надпись
или картинку (рис. 2.78). Декорация не связана с данными
(реквизитами формы) и  обычно выводится для текстовых
пояснений, не изменяемых из встроенного языка.

@image{./Kartinki/2_78}
Рис. 2.78. Элемент формы «Декорация»

@node Дополнение элемента формы, Контекстное меню элементов формы, Элемент формы Декорация, Элементы Формы
@section Дополнение элемента формы
Дополнение элемента формы предназначено для отображения
дополнительных свойств элемента формы (на момент
написания это дополнения таблицы, отображающей данные
динамического списка) и  управления этими элементами. Существуют
следующие дополнения:
@itemize

@item
Отображение строки поиска. Позволяет настроить отображение
строки поиска.

@item
Состояние просмотра. Позволяет настроить отображение
перечня примененных поисковых запросов. Не может располагаться в
командной панели.

@item
Управление поиском. Позволяет настроить внешний вид кнопки
управления поиском (рис. 2.79).

@image{./Kartinki/2_79}
Рис. 2.79. Элемент формы «Дополнение элемента формы»
@end itemize

@node Контекстное меню элементов формы,  , Дополнение элемента формы, Элементы Формы
@section Контекстное меню элементов формы
Для всех элементов формы характерно наличие контекстного меню,
вызываемого с помощью мыши или клавиатуры. В большинстве
случаев во время работы приложения контекстные меню формируются
платформой автоматически. Однако разработчик может вмешаться
в  этот процесс и  повлиять на состав контекстного меню.
@sp 1
Чтобы получить доступ к  контекстному меню элемента формы,
нужно из контекстного меню элемента формы в  редакторе формы
выполнить команду Показать контекстное меню (рис. 2.80).

@image{./Kartinki/2_80}
Рис. 2.80. Доступ к контекстному меню элемента формы
@sp 1
После этого появится возможность добавлять в  контекстное меню
элемента собственные команды. Если разработчик желает модифицировать
автоматически формируемое контекстное меню элемента формы, то флажок
Автозаполнение в  свойствах Контекстное меню элемента снимать не следует
(рис. 2.81). В случае необходимости формирования полностью своего
контекстного меню флажок следует снять.

@image{./Kartinki/2_81}
Рис. 2.81. Автозаполнение контекстного меню
