@node Форма, Элементы Формы, Top, Top
@chapter Форма

Виды элементов формы
В форме используются следующие элементы:
@itemize @bullet
@item
Группа:
@itemize @bullet
@item
Обычная группа ;
@item
Группа  – Страницы ;
@item
Группа  – Командная панель ;
@item
Группа колонок .
@end itemize
@item
Поле .
@item
Кнопка .
@item
Таблица .
@item
Декорация:
@itemize @bullet
@item
Декорация  – Надпись ;
@item
Декорация  – Картинка .
@end itemize
@item
Дополнение элемента формы .
@end itemize

@menu
* Форма группа свойств Основные::
* Форма группа свойств Использование::
* Форма группа свойств Оформление::
* Форма группа свойств Расположение::
@end menu

@node Форма группа свойств Основные, Форма группа свойств Использование, Форма, Форма
@section Форма группа свойств Основные

@menu
* Заголовок::
* АвтоЗаголовок::
* Доступность::
* Разрешить изменять форму::
* Группировка::
@end menu

@node Заголовок, АвтоЗаголовок, Форма группа свойств Основные, Форма группа свойств Основные
@subsection Заголовок

@anchor{свойствоЗаголовок}
Свойство Заголовок определяет заголовок формы, как его будут
видеть разработчик в  окне предварительного просмотра формы
и  пользователь во время работы с формой. Заголовок формы может
быть дополнен системной информацией, полученной из свойств
объекта конфигурации, связанных с расширенным представлением
объектов, списков. Такое влияние на свойство Заголовок возможно,
если установлено свойство АвтоЗаголовок.Например, если задать заголовок формы элемента справочника
Товары   – «Номенклатура», то при открытии товара в  режиме
1С:Предприятие заголовок формы (рис. 2.43) будет состоять из строки
«Номенклатура» плюс название конкретного товара («Босоножки»),
плюс в  скобках представление объекта конфигурации («Товар»).

@image{./Kartinki/2_43}

@node АвтоЗаголовок, Доступность, Заголовок, Форма группа свойств Основные
@subsection АвтоЗаголовок

@anchor{свойствоАвтоЗаголовок}
Если свойство Заголовок не заполнено, а свойство АвтоЗаголовок
включено, то заголовок формы товара будет сформирован полностью
автоматически  – «Босоножки (Товар)». При снятом автозаголовке
и  пустом заголовке заголовок формы будет отсутствовать.
С помощью свойства ОтображатьЗаголовок можно управлять
показом заголовка формы (включая автозаголовок и  признак модификации).
Например, сняв флажок ОтображатьЗаголовок , можно
сэкономить рабочее пространство экрана. Это особенно актуально
для специализированных режимов основного окна приложения Рабочее место ,
Полноэкранное рабочее место и  Киоск .В режиме основного окна приложения
Обычный свойство ОтображатьЗаголовок применяется только для форм,
расположенных на начальной странице.
Когда на начальной странице расположено несколько форм, то вверху
всегда выводится надпись «Начальная страница», а над каждой
формой  – ее собственный заголовок. Можно при желании отключить
показ заголовков форм на начальной странице (рис. ниже).

@image{./Kartinki/2_44}

@node Доступность, Разрешить изменять форму, АвтоЗаголовок, Форма группа свойств Основные
@subsection Доступность

@anchor{свойствоДоступность}
Снятие флажка у свойства Доступность означает, что все элементы
формы недоступны для редактирования пользователем. Кроме
того, ограничить доступность формы можно с помощью свойства
ТолькоПросмотр , которое доступно только из встроенного языка.

@node Разрешить изменять форму, Группировка, Доступность, Форма группа свойств Основные
@subsection Разрешить изменять форму

@anchor{СвойствоРазрешитьИзменятьФорму}
Свойство РазрешитьИзменятьФорму определяет возможность изменения
формы в  пользовательском режиме работы.
Настройка форм в  пользовательском режиме работы является
стандартной возможностью, предоставляемой платформой.
Это означает, что пользователь может изменить порядок элементов
формы, перегруппировать их, изменить их видимость. С помощью
свойства РазрешитьИзменятьФорму такую возможность можно
пресечь. Вместо запрещения изменения всей формы разработчик может
применять «точечные» запреты для конкретных элементов формы.
Свойства, с помощью которых можно запрещать изменения
элементов формы, рассматриваются в  разделах данной главы,
посвященных элементам формы.

@node Группировка,  , Разрешить изменять форму, Форма группа свойств Основные
@subsection Группировка

@anchor{СвойствоГруппировка}
Свойство Группировка определяет режим группировки подчиненных
элементов формы. Возможные значения свойства: Вертикальная ,
Горизонтальная и  Горизонтальная если возможно .
При значении Вертикальная элементы формы располагаются сверху
вниз. При значении Горизонтальная элементы будут располагаться
слева направо. При значении Горизонтальная если возможно
применяется горизонтальная группировка при наличии достаточного
места по ширине формы. В противном случае  – вертикальная
группировка

@image{./Kartinki/2_47}

Настройка влияет только на элементы верхнего уровня иерархии
подчиненных элементов. Порядок расположения элементов формы,
находящихся внутри групп, определяется свойством Группировка
соответствующей группы элементов.


@node Форма группа свойств Использование, Форма группа свойств Оформление, Форма группа свойств Основные, Форма
@section Форма группа свойств Использование

@menu
* ОтображатьЗаголовок::
* Положение командной панели::
* Режим открытия окна::
* Проверять заполнение автоматически::
* Список групп::
@end menu

@node ОтображатьЗаголовок, Положение командной панели, Форма группа свойств Использование, Форма группа свойств Использование
@subsection ОтображатьЗаголовок

@anchor{свойствоОтображатьЗаголовок}
Если же на начальной странице располагается только одна
форма и  свойство ОтображатьЗаголовок включено, то заголовок
формы выводится вместо надписи «Начальная страница».
Если флажок ОтображатьЗаголовок снят, то вместо заголовка формы
выводится надпись «Начальная страница».

@image{./Kartinki/2_45}

@node Положение командной панели, Режим открытия окна, ОтображатьЗаголовок, Форма группа свойств Использование
@subsection Положение командной панели

@anchor{СвойствоПоложениеКоманднойПанели}
Свойство ПоложениеКоманднойПанели определяет положение
командной панели формы. Свойство может принимать одно
из четырех значений: Нет , Авто , Верх , Низ (рис. ниже). По умолчанию
системой устанавливается значение Авто . Это означает, что решение
о расположении командной панели принимается платформой.

@image{./Kartinki/2_46}

@node Режим открытия окна, Проверять заполнение автоматически, Положение командной панели, Форма группа свойств Использование
@subsection Режим открытия окна

@anchor{СвойствоРежимОткрытияОкна}
Свойство РежимОткрытияОкна определяет, в  каком окне будет
открываться форма. Возможны значения Независимый , Блокировать
окно владельца и  Блокировать весь интерфейс.
В режиме Независимый форма открывается в  рабочей области
основного окна приложения. При этом окно формы не препятствует
возможности переключения между окнами приложения. В таком
режиме форма живет своей, не мешающей остальным формам
жизнью.
В режиме Блокировать окно владельца форма открывается в  блоки-
рующем окне, при этом работа с формой, из которой инициировано
открытие текущей формы, блокируется. Данный режим предназначен
для форм, в  которых вводится мало информации и  работа
с которыми не требует длительного времени, например для ввода
элементов справочников, содержащих небольшое количество
реквизитов. Этот режим внешне аналогичен модальному открытию
формы, однако при открытии из встроенного языка работа
модуля не останавливается на время работы открываемой формы.
При открытии происходит блокировка только «родительского» окна,
другие окна приложения остаются доступными.
В режиме Блокировать весь интерфейс форма открывается
в  блокирующем окне, при этом блокируется работа не только
с родительской формой, но со всем интерфейсом прикладного
решения. Окна, блокирующие весь интерфейс, обеспечивают
работу приложения без использования модальных окон.
Отказ от модальности является необходимым условием для работы
«1С:Предприятия» в  веб-клиенте и  на мобильных устройствах,
а также по ряду других причин.

@node Проверять заполнение автоматически, Список групп, Режим открытия окна, Форма группа свойств Использование
@subsection Проверять заполнение автоматически

@anchor{свойствоПроверятьЗаполнениеАвтоматически}
Установленный флажок у свойства ПроверятьЗаполнениеАвтоматически
означает автоматическую проверку заполнения реквизитов
формы при работе пользователя.

@node Список групп,  , Проверять заполнение автоматически, Форма группа свойств Использование
@subsection Список групп

@anchor{свойствоСписокГрупп}
С помощью свойства СписокГрупп можно поддерживать автоматическую
синхронизацию данных в  форме, когда в  ней
отображаются одновременно список групп и  собственно содержимое
иерархического справочника. Это свойство становится доступным
в  том случае, если основным реквизитом формы выступает
реквизит типа ДинамическийСписок .
Для этого в  свойстве формы СписокГрупп нужно указать таблицу,
отображающую динамический список, который показывает только
иерархию групп отображаемого справочника (рис. ниже).

@image{./Kartinki/2_49}

В этом случае при выборе группы в  списке групп в  списке элементов
будет отображаться содержимое выбранной группы, и  наоборот
(рис. ниже).

@image{./Kartinki/2_50}

@node Форма группа свойств Оформление, Форма группа свойств Расположение, Форма группа свойств Использование, Форма
@section Форма группа свойств Оформление

@menu
* Вертикальная прокрутка::
* Условное оформление::
* Вариант масштаба::
@end menu

@node Вертикальная прокрутка, Условное оформление, Форма группа свойств Оформление, Форма группа свойств Оформление
@subsection Вертикальная прокрутка

@anchor{свойствоВертикальнаяПрокрутка}
С помощью свойства ВертикальнаяПрокрутка можно управлять
отображением вертикальной прокрутки формы, а также тем, как
будут вести себя элементы формы в  том случае, если форма будет
сжиматься по вертикали.
Возможны следующие режимы включения вертикальной прокрутки
формы:

@itemize @bullet
@item
Использовать   – полоса вертикальной прокрутки появится после
того, как вертикальный размер элементов формы достигнет
размера, который был задан при редактировании формы в  конфигураторе;

@item
Использовать без растягивания   – при растягивании формы
элементы формы не будут реагировать на изменение размера
формы;

@item
Использовать при необходимости   – перед появлением полосы
прокрутки элементы формы будут сжиматься по вертикали до
своего минимального размера. Если они все-таки не поместятся
в  форме, появится полоса прокрутки;

@item
Авто   – поведение формы зависит от типа основного реквизита
формы. Если основной реквизит формы имеет тип
ДинамическийСписок или ОтчетОбъект , то свойство ВертикальнаяПрокрутка
принимает значение Использовать при необходимости .
В остальных случаях  – значение Использовать .
@end itemize

На рис. 2.48 продемонстрированы различия режимов включения
вертикальной прокрутки формы.
При значении Использовать (см. рис. 2.48 слева внизу) вертикальная
прокрутка появляется сразу же, как только форма сжимается по вертикали
относительно своего исходного размера. При этом все элементы
формы, в  т. ч. картинка товара, имеют свой реальный размер.
При значении Использовать при необходимости элементы формы
сжимаются так, чтобы избежать вертикальной прокрутки формы.
В частности, при такой же высоте формы, что и  в  предыдущем
случае, картинка товара сжимается и  полоса прокрутки отсутствует
(см. рис. 2.48 справа внизу). Но если элементы формы сжаты максимально
и  все равно не умещаются по высоте формы, то вертикальная
прокрутка формы появляется (см. рис. ниже справа вверху).
Стандартно свойство ВертикальнаяПрокрутка устанавливается
в  значение Авто . Менять его, как правило, нет необходимости.
Исключением являются формы, имеющие поля для вывода HTML-
документов, форматированных документов, текстовых документов,
табличных документов (кроме форм отчетов). Для таких форм
свойство Вертикальная прокрутка должно быть установлено
в  значение Использовать при необходимости .

@image{./Kartinki/2_48}

рис. 2.48

@node Условное оформление, Вариант масштаба, Вертикальная прокрутка, Форма группа свойств Оформление
@subsection Условное оформление

@anchor{свойствоУсловноеОформление}
Гиперссылка Открыть у свойства УсловноеОформление позволяет
открыть окно Настройка условного оформления . В данном окне можно
можно настроить, например, выделение цветом некоторого элемента в
зависимости от значений других элементов формы.

@node Вариант масштаба,  , Условное оформление, Форма группа свойств Оформление
@subsection Вариант масштаба

@anchor{свойствоВариантМасштаба}
Свойство ВариантМасштаба определяет, каким образом форма будет
отображаться в  интерфейсе Такси :
@itemize @bullet
@item
Авто   – режим отображения формы определяется автоматически
на основе анализа значения свойства ВариантМасштабаФормКлиентскогоПриложения
объекта НастройкиКлиентскогоПриложения .
Если в  данном свойстве не указано конкретное значение варианта
масштаба, то в  интерфейсе Такси значение Авто будет трактоваться как Обычный .

@item
Обычный   – форма выглядит стандартно для интерфейса Такси .
На размер формы влияет свойство Масштаб .

@item
Компактный   – в  этом случае форма выглядит «почти»
как в  интерфейсе версии 8.2. Свойство Масштаб не оказывает
влияния на размер формы.
@end itemize

С помощью свойства ВариантМасштаба можно управлять отображением
одной формы, разрабатываемой в  конфигураторе. Она может
выглядеть в  обычном или компактном масштабе.
Чтобы изменить вариант масштаба сразу всех форм прикладного
решения, нужно программно установить значение свойства
ВариантМасштабаФормКлиентскогоПриложения объекта
НастройкиКлиентскогоПриложения .
Компактный вариант масштаба может использоваться для быстрого
перевода сложных насыщенных форм с интерфейса Версия 8.2
на интерфейс Такси . Чтобы, не переделывая саму форму, быстро
уменьшить масштаб ее отображения примерно до 80 %.



@node Форма группа свойств Расположение,  , Форма группа свойств Оформление, Форма
@section Форма группа свойств Расположение

@menu
* Масштаб::
@end menu

@node Масштаб,  , Форма группа свойств Расположение, Форма группа свойств Расположение
@subsection Масштаб

@anchor{свойствоМасштаб}
Если форма будет использоваться только в  интерфейсе Такси , то
лучше уменьшать/увеличивать масштаб формы с помощью
свойства Масштаб . Данное свойство указывает, каким должен быть
масштаб данной формы относительно ее базового размера (в процентах).
Значение свойства может изменяться от 10 до 400. Свойство Масштаб
не применяется для форм с компактным изображением.
Масштаб, установленный в  клиентском приложении, накладыва
ется на масштаб, указанный в  конфигураторе для каждой формы.
Таким образом, если в  конфигураторе установлен масштаб формы
70 %, а в  клиентском приложении установлен масштаб 50 %, то
результирующий масштаб будет 35 % от реального размера формы.

