@node Все свойства формы, , Элемент формы Поле, Top
@chapter Все свойства Формы

@menu
* свойства Управляемая форма::
@end menu

@node свойства Управляемая форма,  , Все свойства формы, Все свойства формы
@section свойства Управляемая форма

@ref{свойствоАвтоЗаголовок,,АвтоЗаголовок} @*
АвтоНавигационнаяСсылка
АвтоматическоеСохранениеДанныхВНастройках
@ref{свойствоВертикальнаяПрокрутка,,ВертикальнаяПрокрутка}@*
@ref{свойствоВариантМасштаба,,ВариантМасштаба}@*
ВертикальноеПоложениеПодчиненных
ВертикальныйИнтервал
ВладелецФормы
ВыравниваниеЭлементовИЗаголовков
Высота
ГоризонтальноеПоложениеПодчиненных
ГоризонтальныйИнтервал
@ref{СвойствоГруппировка,,Группировка}@*
@ref{свойствоДоступность,,Доступность}@*
@ref{свойствоЗаголовок,,Заголовок}@*
ЗакрыватьПриВыборе
ЗакрыватьПриЗакрытииВладельца
ИмяФормы
КлючНазначенияИспользования
КлючСохраненияПоложенияОкна
КлючУникальности
КоманднаяПанель
Команды @*
@ref{свойствоМасштаб,,Масштаб}@*
МодальныйРежим
Модифицированность
НавигационнаяСсылка
Окно
ОписаниеОповещенияОЗакрытии @*
@ref{ОтображатьЗаголовок,,ОтображатьЗаголовок}@*
ОтображатьКнопкуЗакрытия
ОтображениеОбсуждений
Параметры
ПоведениеКлавишиEnter
ПодчиненныеЭлементы@*
@ref{СвойствоПоложениеКоманднойПанели,,ПоложениеКоманднойПанели}@*
@ref{свойствоПроверятьЗаполнениеАвтоматически,,ПроверятьЗаполнениеАвтоматически}@*
@ref{СвойствоРазрешитьИзменятьФорму,,РазрешитьИзменятьФорму}@*
@ref{СвойствоРежимОткрытияОкна,,РежимОткрытияОкна}@*
СворачиваниеЭлементовПоВажности
СохранениеДанныхВНастройках
СохраняемыеВНастройкахДанныеМодифицированы@*
@ref{свойствоСписокГрупп,,СписокГрупп}@*
ТекущийЭлемент
ТолькоПросмотр
УникальныйИдентификатор@*
@ref{свойствоУсловноеОформление,,УсловноеОформление}@*
Ширина
ШиринаПодчиненныхЭлементов
Элементы
ЭтаФорма
ЭтотОбъект
