@node Типы Элементов формы
@chapter Типы Элементов формы

@itemize
@item
группа Обычная группа@*
В такую группу можно включить все типы верхнего уровня
@item
группа Обычная группа без отображения
@item
группа Страницы
@item
группа Командная панель
@item
Поле
@item
Кнопка
@item
Таблица
@item
Декорация Надпись
@item
Картинка
@item
Дополнение элемента формы
@end itemize
