\input texinfo  
@setfilename uf.info
@documentencoding UTF-8
@settitle Управляемый интерфейс

@node Top, Форма, (dir), (dir)
@top Управляемый Интерфейс

@menu
* Форма::                       
* Элементы Формы::              
* Элемент формы Поле::          
* Все свойства формы::          

@detailmenu
 --- The Detailed Node Listing ---

Форма

* Форма группа свойств Основные::
* Форма группа свойств Использование::
* Форма группа свойств Оформление::
* Форма группа свойств Расположение::

Форма группа свойств Основные

* Заголовок::
* АвтоЗаголовок::
* Доступность::
* Разрешить изменять форму::
* Группировка::

Форма группа свойств Использование

* ОтображатьЗаголовок::
* Положение командной панели::
* Режим открытия окна::
* Проверять заполнение автоматически::
* Список групп::

Форма группа свойств Оформление

* Вертикальная прокрутка::
* Условное оформление::
* Вариант масштаба::

Форма группа свойств Расположение

* Масштаб::

Элементы Формы

* Элемент формы Группа::
* Элемент формы Таблица::
* Элемент формы Кнопка::
* Элемент формы Декорация::
* Дополнение элемента формы::
* Контекстное меню элементов формы::

Элемент формы Поле

* Элемент формы Поле вида Поле ввода::

Элемент формы Поле вида Поле ввода

* Поле ввода группа свойств Основные::
* Поле ввода группа свойств Использование::
* Поле ввода группа свойств Оформление::
* Поле ввода группа свойств Расположение::
* Поле ввода группа свойств События::

Поле ввода группа свойств Основные

* Маска::
* РежимПароля::

Поле ввода группа свойств Использование

* ВыбиратьТип::
* СписокВыбора::

Поле ввода группа свойств Оформление


Поле ввода группа свойств Расположение


Поле ввода группа свойств События


Все свойства Формы

* свойства Управляемая форма::

@end detailmenu
@end menu

@include forma.texi
@include ElementuFormu.texi
@include pole.texi
@include FormaVseSvoistva.texi
@bye
