\input texinfo
@setfilename Чпаргалка.info
@settitle Моё превое руководство 1.0
@copying
Здесь краткое описание руководства 1.0
@quotation
Разрешается...
@end quotation
Copyright @copyright{} 2016 Обинякин Алексей Станиславович, корпорация Рассвет.
@end copying
@titlepage
@title Это титульный лист для печатной версии
@subtitle 
@subtitle
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage
@c Вывод таблицы содержимого в начале.
@contents
@ifnottex
@node Top
@top Первое моё руководство
Это моё первое руководство
@c (version @value{VERSION}, @value{UPDATED}).
@end ifnottex
@menu
* Первая Глава::    Первая и единственная глава
                    данного примера руководства.
* Index::            Полный индекс.
@end menu
@node Первая Глава
@chapter Первая Глава
@cindex глава, первая
     Это первая глава.
@cindex запись индекса, другой
Вот пронумерованный список.
@enumerate
@item
     Это первый пункт списка.
@item
     Это второй пункт списка.
@end enumerate
@node Index
@unnumbered Index
@printindex cp
@bye
